<?php
/**
 * @author Mniziolek Team
 * @copyright Copyright (c) Mniziolek (https://github.com/niziou/)
 */
/** @var \Mniziolek\Preorder\Block\Product\View\Preorder $block */

if ($block->isPreorderActive()): ?>
    <div class="product-info-form-row product-preorder">
        <div class="box-tocart">
            <div class="fieldset">
                <div class="actions">
                    <button data-mage-init='{"preorder-modal": {}}'
                            type="button"
                            title="<?= __('Preorder'); ?>"
                            class="action primary product-preorder-button"
                            id="product-preorder-button"
                            data-toggle="modal"
                            data-target="#preorderModal">
                        <span><?= __('Preorder'); ?></span>
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="preorderModal" role="dialog" style="display:none;">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title"><?= __('Preorder Form') ?></h4>
                                </div>
                                <div class="modal-body">
                                    <div id="preorder-message" style="display: none;"></div>
                                    <div id="preorder-form">
                                        <div class="form-group">
                                            <label for="email"><?= __('E-mail address'); ?>:</label>
                                            <input type="email" class="form-control" id="email" name="email">
                                        </div>
                                        <div class="form-group">
                                            <label for="firstname"><?= __('First name'); ?>:</label>
                                            <input type="email" class="form-control" id="firstname" name="firstname">
                                        </div>
                                        <div class="form-group">
                                            <label for="surname"><?= __('Surname'); ?>:</label>
                                            <input type="email" class="form-control" id="surname" name="surname">
                                        </div>
                                        <div class="form-group">
                                            <label for="street[0]"><?= __('Address Line 1'); ?>:</label>
                                            <input type="email" class="form-control" id="street[0]" name="street[0]">
                                        </div>
                                        <div class="form-group">
                                            <label for="street[1]"><?= __('Address Line 2'); ?>:</label>
                                            <input type="email" class="form-control" id="street[1]" name="street[1]">
                                        </div>
                                        <div class="form-group">
                                            <label for="city"><?= __('City'); ?>:</label>
                                            <input type="email" class="form-control" id="city" name="city">
                                        </div>
                                        <div class="form-group">
                                            <label for="zip"><?= __('Zip code'); ?>:</label>
                                            <input type="email" class="form-control" id="zip" name="zip">
                                        </div>
                                        <div class="form-group">
                                            <label for="country"><?= __('Country'); ?>:</label>
                                            <input type="email" class="form-control" id="country" name="country">
                                        </div>
                                        <div class="form-group">
                                            <label for="mobile"><?= __('Mobile number'); ?>:</label>
                                            <input type="email" class="form-control" id="mobile" name="mobile">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <input type="hidden" id="product_id" name="product_id" value="<?= $block->getProduct()->getId(); ?>">
    </div>
<?php endif;

